server:
  port: 8761                    # 指定该Eureka实例的端口

spring:
  application:
    name: discovery-eureka

eureka:
  instance:
    hostname: discovery         # 指定该Eureka实例的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/