server:
  port: 8000

spring:
  application:
    name: engine
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&useSSL=false
    username: root
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate.hbm2ddl.auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
#    instance:
#      preferIpAddress: true